### ISSUE TITLE
Peer Review- Sabrina

### ISSUE THREAD

**Issue by schen1224** [lulillian/WebtechProject#1]
Hi Lillian, I love your website! I also love dogs, so it is good to see your website is about dog adoption. Your codes are clear to read and I enjoy reading them! 

I have a few technical suggestions here to probably help you to improve your website: 
1. Instead of using many `<br>`, maybe you can use margin in CSS to make empty spaces.
https://github.com/lulillian/WebtechProject/blob/ada5379a61b5aa51ffa7d3b77f592c89248fa58b/index.html#L77
2. I think` </span>` is extra here.
https://github.com/lulillian/WebtechProject/blob/ada5379a61b5aa51ffa7d3b77f592c89248fa58b/index.html#L70
3. Maybe use more id instead of class if you only reference once. 
https://github.com/lulillian/WebtechProject/blob/ada5379a61b5aa51ffa7d3b77f592c89248fa58b/index.html#L57-L61
5. I am not sure if it is my problem, but I can't go to any other pages except the adoption page from your home page. Other pages are only accessible if I am not on the home page. I checked your code which looks fine to me, so I am not sure if it is my problem. 

Content Suggestions:
I love your consistency throughout the website! You used the same font, color, and size. 
1. Maybe you should consider changing the color of the text here to a lighter one? The dark text color and the dark background are kind of hard to read. 
<img width="400" alt="Screen Shot 2022-11-06 at 2 16 18 PM" src="https://user-images.githubusercontent.com/112512892/200190451-73c952ea-0219-423f-944c-3cdf0d2797e6.png">
2.  Maybe considering add some links to the adoption center on your adoption page, so people who are interested can easily find more adoption information. 
<br>
Please don't hesitate to let me know if you have any questions. I am excited to see your final version of the project! I believe it would be awesome! 🐶  🐶  🐶

**Comment by lulillian** [comment]
Thank you for the feedback!
