### ISSUE TITLE
Peer Review- Yirong Shen

### ISSUE THREAD

**Issue by yshen12138** [lulillian/WebtechProject#2]
Hi Lillian, I really liked your website. The font you used for the homepage is very cool, and all the information are clearly listed.

Technical Issue: 1. The resources, contact and site map link on the navigation bar is not working unless I visit adopt site first. But I can 
                               not  figure out what caused that since from my site, your codes should worked. 
                         2.  In your resources page, instead of labeling a lot of classes, maybe use ids instead to make it more clear.

Content suggestion: 1. At the bottom of your resource page, the three logos have different sizes, maybe consider make the size 
                                     identical so the page looks better.
                                 2. Maybe add more css to contact page.

**Comment by lulillian** [comment]
Thanks for the feedback!
